[project]
name = "adv-text2sql"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "pydantic",
    "pydantic-ai",
    "logfire",
    "pydantic-evals[logfire]",
    "autogen-agentchat",
    "autogen-ext",
    "openai",
    "tiktoken",
    "mcp",
    "fastmcp",
    "openai",
    "python-dotenv",
    "sqlglot",
    "sqlalchemy",
    "psycopg[binary]",
    "tabulate",
    "pymupdf",
    "pandas",
    "python-docx",
    "openpyxl",
    "func_timeout",
    "networkx>=3.6.1",
    "sentence-transformers>=5.6.1",
]

[dependency-groups]
dev = [
    "ruff",
    "pyrefly",
]
test = [
    "pytest",
]
client = [
    "autogen-agentchat",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["src/partial_mcp"]
